### ISSUE TITLE
Добавление треков и точек без категории

### ISSUE THREAD

**Issue by seekerk** [oss-fruct-org/gets#12]
API допускает добавление точек и треков без указания категории. При этом, если не указать категорию то возникает проблема с чтением созданных объектов. Необходимо создать в конфиг файле параметр "категория по умолчанию" и для создаваемых точек и треков при отсутствии категории указывать категорию по умолчанию.

**Comment by ivashov** [comment]
Добавил настройку DEFAULT_CATEGORY_ID

**Comment by seekerk** [comment]
Ошибка продолжает воспроизводиться. В частности, если через web интерфейс отправить запрос на добавление, то в БД добавляется запись с ID категории = -1.

**Comment by ivashov** [comment]
При указании категории "none" web-интерфейс передает -1 в поле category_id, а createTrack позволяет добавить точку с null-категорией если это явно указано.

Нужно сделать чтобы указание -1 означало default_category. Также надо будет добавить для категории по умолчанию поле <default> в выводе getCategories и убрать из интерфейса пункт none (он все равно бессмысленный, т.к. у трека без категории нет привязки к сервису).
