### ISSUE TITLE
Предоставление доступа к трекам другим пользователям

### ISSUE THREAD

**Issue by seekerk** [oss-fruct-org/gets#17]
Реализовать возможность подписки к трекам других пользователей и возможность расшаривания треков других пользователей.

Вариант решения: создать таблицу расшаренных треков (ИД трека, ключ) и по ключу предоставлять функцию подписки

Необходимые изменения в сервисе:
- новая функция шаринга трека (запись в таблицу расшаренных треков)
- обновление функции просмотра треков (для каждого трека показывать статус шаринга с ключом (если есть) и показывать треки других пользователей)
- функция подписки по ключу шары
- проверить функцию отписки
- функция отмены шаринга (удаление из таблицы расшаренных треков и отмена всех подписок других пользователей)

**Comment by ivashov** [comment]
>функция подписки по ключу шары

Подписка должна давать возможность загрузить содержимое трека? Или ключ должен передаваться в loadTrack.php

>по ключу предоставлять функцию подписки

ключ общий для всех пользователей? если это нужно для платной подписки, возможно есть смысл сделать приватные ключи, вычисляемые например так sha1 (email + master_track_key).

**Comment by seekerk** [comment]
> Подписка должна давать возможность загрузить содержимое трека? Или ключ должен передаваться в loadTrack.php?

Думаю, что не надо передавать ключ в loadTrack.php. После подписки трек появляется наравне с остальными в loadTracks.php

> ключ общий для всех пользователей? если это нужно для платной подписки, возможно есть смысл сделать приватные ключи, вычисляемые например так sha1 (email + master_track_key).

Можно в таблицу расшаренных треков добавить поле количества доступных шар (-1 = бесконечность) и при выполнении шаринга уменьшать положительное значение на 1. Тогда можно будет сделать и публичные шары "для всех" и персональные "платные".

**Comment by ivashov** [comment]
>После подписки трек появляется наравне с остальными в loadTracks.php

А как тогда пользователь узнает, что трек существует? Нужно наверное добавить параметр в loadTracks.php "show_shared_tracks".

>Можно в таблицу расшаренных треков добавить поле количества доступных шар

Есть ли смысл? Для публичных треков можно просто не указывать ключ в БД и позволить подписываться всем, для приватных генерировать приватный ключ на основе email'а пользователя и ключа трека.

**Comment by ivashov** [comment]
Хотя нумерация позволит выложить ключ трека и позволить использовать его к примеру 10 раз. Кто успел, тот и подписался. Думаю объединить эти два варианта будет не сложно.

**Comment by ivashov** [comment]
API получается такой

shareTrack.php
* auth_token
* name - track id
* private - нужен ли ключ
* limit - сколько раз можно подписаться
* Возвращается ключ в виде строки

unshareTrack.php — должно убрать все подписки
* auth_token
* name - track id

subscribe.php
* auth_token
* name
* key - опционально
* Возвращает success/failure

unsubscribe.php
* auth_token
* name

loadTracks.php
* show_shared - значения all, trusted, none — чтобы отфильтровать тестовые треки от случайных пользователей
* В возвращаемый xml добавляется boolean-поле shared

Нужно подумать, что делать при отписке от трека — увеличивать ли лимит.

**Comment by seekerk** [comment]
> А как тогда пользователь узнает, что трек существует? Нужно наверное добавить параметр в loadTracks.php "show_shared_tracks".

Планировалось что пользователь, расшаривший трек, будет распространять ссылку на подписку через сторонние ресурсы, например, через социальные сети. Таким образом, если тебе пришла ссылка на расшаренный трек, ты можешь подписаться на его через веб интерфейс запустив функцию subscribe.php (реализация вызова на стороне веб интерфейса). Просматривать расшаренные треки через loadTracks.php бессмысленно, т.к. для этого есть публичное пространство. 
В случае платных треков, пользователь будет покупать строковое значение ключа с количеством подписок и распространять его на группу пользователей (например, пользователь купил ключ и подписал своих друзей на этот ключ).

В shareTrack.php limit - опциональное поле, действует если трек не публичный и по умолчанию значение 1.

В subscribe.php не вижу необходимости на указание name при наличии key. Если оно надо, то пусть будет.

В loadTracks.php указывать shared смысла нет, расшаренный трек будет для пользователя публичным и он будет иметь права на чтение по умолчанию.

При отписке от трека надо увеличивать лимит, т.к. пользователь не сможет повторно подписаться с ключом.

**Comment by ivashov** [comment]
теперь понятно, сразу не понял смысл ключей.

>Если оно надо, то пусть будет.

нет, в таком варианте это не нужно.

**Comment by ivashov** [comment]
>В shareTrack.php limit - опциональное поле, действует если трек не публичный

Это непонятно. У пользователя без trusted-прав не может быть публичных треков. Наверное лучше сделать полю limit вариант значения unlimited.

**Comment by seekerk** [comment]
>> В shareTrack.php limit - опциональное поле, действует если трек не публичный

> Это непонятно. У пользователя без trusted-прав не может быть публичных треков. Наверное лучше сделать полю limit вариант значения unlimited.

Имеется в виду не публичный трек, а публичное использование шары трека. Давай тогда поле limit будет принимать значение по умолчанию unlimited, а если владелец захочет ограничить количество подписок, то он задаст числовое значение. 

Поле private можно, кстати, убрать, т.к. в любом случае для подписки нужен ключ.

**Comment by ivashov** [comment]
Пока сделал возможность создавать несколько ключей с разными лимитами для одного трека. 

Нужно ли это? 

Если не нужно, это упростит отмену шаринга и отписку, т.к. не нужно будет хранить по какому ключу пользователь подписывался. Если нужно, потребуется еще одна таблица.

**Comment by ivashov** [comment]
Оказывается у таблицы subscribe в качестве ключа пара (user_id, channel_id), так что придется её дублировать или добавлять ей третье поле.

**Comment by seekerk** [comment]
Можно добавлять поля с учетом обратной совместимости с geo2tag, т.е. БД должна работать и с настоящим geo2tag сервером который не знает про эти модификации.

**Comment by ivashov** [comment]
Почти все сделано, но наверное нужно еще в loadTracks.php возвращать является ли трек подписанным по ключу или он публичный.

Также подписка сейчас сделана по ключу, а отписка по id трека. 

unshareTrack принимает ключ трека, и убирает только 'шару' связанную с этим ключом.
