### ISSUE TITLE
Поддержка нескольких фото

### ISSUE THREAD

**Issue by seekerk** [oss-fruct-org/gets#19]
в БД фото могут храниться в виде массива:
{
    "description" : "Point description",
    "photo" : ["http://example.com/1.png", "http://example.com/2.png"]
} 
Надо добавить: 
- возможность указания несколько фото для одной точки
- просмотр перечня фото для точки
- отображение первого фото в описании точки

Пример для проверки: http://gets.cs.petrsu.ru/gets/web-client/dist/tracks.php?lang=en#form=point_info&track_id=tr+ka322enpi@gmail.com+Кемь+ru_RU&point_uuid=0e8a1547-38ee-4b84-a07e-c850a4dbace1

**Comment by ivashov** [comment]
>возможность указания несколько фото для одной точки

В gets это уже реализовано, но на сервер пока не выложено.

**Comment by davydovsky** [comment]
После создания точки с несколькими фото, метод loadTrack, возвращает в поле link массив photos. Эти же фото есть в тегах <gets:photo> и получется настоящие значение link теряется. 
Пример: 
...
<Data name="link">
    <value>{"photo":["http%3A%2F%2Flocalhost%2Fassets%2F1.jpg","http%3A%2F%2Flocalhost%2Fassets%2F2.jpg","http%3A%2F%2Flocalhost%2Fassets%2F3.jpg"]}</value>
</Data>
<gets:photo>http%3A%2F%2Flocalhost%2Fassets%2F1.jpg</gets:photo>
<gets:photo>http%3A%2F%2Flocalhost%2Fassets%2F2.jpg</gets:photo>
<gets:photo>http%3A%2F%2Flocalhost%2Fassets%2F3.jpg</gets:photo>
...

К чему такое дублирование? И как полуить значение link?
Кстати, addPoint возвращает корректное значение link.

**Comment by ivashov** [comment]
Это косяк буду разбираться.

**Comment by ivashov** [comment]
В репозитории новая версия, эта проблема исправлена.

**Comment by davydovsky** [comment]
>В репозитории новая версия, эта проблема исправлена.
Спасибо.

А в updatePoint сейчас есть возможность работы с несколькими фото?

**Comment by ivashov** [comment]
Нет, но завтра сделаю.

**Comment by ivashov** [comment]
Сделал, формат тот что что в addPoint.php. Массив фото заменяется полностью.
