### ISSUE TITLE
Удаление точки

### ISSUE THREAD

**Issue by alexwine** [oss-fruct-org/gets#26]
Не удается удалить точку.

Отправляю:
```xml
<request>
<params>
<auth_token>мой_токен</auth_token>
<category_id>23</category_id>
<uuid>20e1391d-c0fe-4774-9f58-39203068de98</uuid>
<latitude>61.75950241088867</latitude>
<longitude>34.36360168457031</longitude>
<time>03 04 2015 12:33:59.000000</time>
<description></description>
</params>
</request>
```
Ответ сервера:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<response>
<status>
<code>0</code>
<message>Tag successfully removed</message>
</status>
<content>success</content>
</response>
```
При следуещем получении точек ничего не изменяется (точка на месте). И ответ сервера немного не соответствует желаемому: была попытка удаления точки, а не тега.

**Comment by ivashov** [comment]
Я посмотрел в базе данных, у этой точки другие координаты. Требуется точное совпадение. Вообще, я не вижу смысла при удалении точки указывать что-либо кроме uuid. 

Если необходимо  удаление по координатам, могу сделать указание радиуса в котором удалять точки.

>И ответ сервера немного не соответствует желаемому: была попытка удаления точки, а не тега.
Это одно и то же, но 'success' нужно заменить на количество удаленных точек.

**Comment by alexwine** [comment]
Я согласен, что UUID достаточно для удаления, но при отправке только идентификатора возникает другая проблема.
Отправляю: 
```xml
<request>
<params>
<auth_token>мой_токен</auth_token>
<uuid>b262a21e-fca1-4830-8972-6c47247ce85b</uuid>
</params>
</request>
```
Получаю:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<response>
<status>
<code>1</code>
<message>Error: not valid input XML document.</message>
</status>
</response>
```

**Comment by ivashov** [comment]
track_name или category_id обязательны

**Comment by alexwine** [comment]
Теперь работает. Спасибо.

**Comment by alexwine** [comment]
Похоже, что проблема все еще существует.

Запрос:
```xml
<request><params><auth_token>токен</auth_token><category_id>26</category_id><uuid>5ecc38e4-62b8-45d4-9872-1952ca4eca59</uuid></params></request>
```
Ответ:
```xml
<?xml version="1.0" encoding="UTF-8"?><response><status><code>0</code><message>Tag successfully removed</message></status>
<content>success</content></response>
```
Но точка не удаляется с сервера и продолжает отображаться при следующем получении точек. Было предположение, что это из-за прав доступа, но у точек есть права на запись. Например, точка с uuid=3fa67ba3-ac72-4ed5-9427-92765cc88d83 обладает правами rw, но не удаляется (хотя при удалении сервер дает успешный ответ об удалении). Попытка обновления данных точки тоже не приводит к успеху, хотя сервер опять же отвечает успехом.

**Comment by ivashov** [comment]
Да, вижу где проблема. Насколько это срочно?

**Comment by alexwine** [comment]
Не срочно.

**Comment by ivashov** [comment]
В тестовой ветке сделано, сегодня-завтра потестирую и выложу все на сервер

**Comment by alexwine** [comment]
Ок, тогда жду закрытия бага :)

**Comment by ivashov** [comment]
На прошлой неделе не получилось, возникли другие срочные задачи.
