### ISSUE TITLE
Неверно сохраняются URL

### ISSUE THREAD

**Issue by ivashov** [oss-fruct-org/gets#27]
При создании точки из web-интерфейса, audio и photo url'ы сохраняются в формате url-encoded.
Возвращается в таком виде

`<gets:photo>http%3A%2F%2Fexample.com%2Ftest.png</gets:photo>`

Возможно, проблема здесь: https://github.com/oss-fruct-org/gets/blob/master/web-client/src/scripts/gets/models/Points.Class.js#L217 

С этой ошибкой создан гид "Кемь" (может и другие, пока не смотрел)

**Comment by davydovsky** [comment]
Это было сделано специально, т.к. на сервере не проходили валидацию некоторые xml-запросы, судя по всему именно из-за url-ов.

Пример проблемного url:
```
<request>
  <params>
    <auth_token>g....</auth_token> 
    <uuid>de62e0e4-00b5-dbdc-8389-bf151fb00188</uuid>
    <title>Putinki</title>
    <description>Putinki</description>
    <link>http://www.mohko.net/</link>
    <extended_data>
      <radius>0</radius>
      <audio>https://docs.google.com/uc?id=0B2XNIk4OEU7wOXVnV1h3bVFkU1U&export=download</audio>
    </extended_data>
    <photos>
      <photo>https://docs.google.com/uc?id=0B2XNIk4OEU7weDNzeGpXWVVJZTQ&export=download</photo>
    </photos>
    <latitude>62.6373781</latitude>
    <longitude> 31.2811661</longitude>
    <altitude>0</altitude>
    <channel>tr+seeker.k@gmail.com+mohko, the former ironworks+en_US</channel>
  </params>
</request>
```

Валидатор www.xmlvalidation.com, показывает, что ошибка именно в url. 
Если encoded url-ы вызывают какие-то критические ошибки, то буду искать другое решение проблемы.

**Comment by ivashov** [comment]
XML не валидируется, потому что в URL-е есть амперсанды. Экранировать их нужно не при формировании JSON'а, который отправляется скриптам на сервере (у json'а свои правила экранирования, которые обрабатывает jQuery и json_decode), а уже в php-скрипте при формировании XML'а при помощи htmlspecialchars() или встроенных XML-библиотек, но никак не url-encode'а, который предназначен совсем для другого.

Мне кажется, для решения проблемы достаточно убрать все экранирования и деэкранирования из web-клиента и добавить htmlspecialchars в traversArray в файле array2xml.inc (34 строка).

Что делать с уже созданными треками я пока не знаю, но если их не много, наверное легче всего их поправить руками.

>Если encoded url-ы вызывают какие-то критические ошибки

Любая библиотека разбора XML вернёт эти "url"-ы как есть, т.е. `http%3A%2F%2Fexample...`, что конечно же не является правильным URL'ом.

**Comment by davydovsky** [comment]
ок, тогда уберу encode/decode и буду использовать htmlspecialchars(). 
А по трекам, насколько я знаю, через web-интерфейс был сделан только трек - "Кемь"

**Comment by davydovsky** [comment]
Убрал encode/decode и исправил url-ы в треке "Кемь"
