### ISSUE TITLE
Обновление имени треков не работает

### ISSUE THREAD

**Issue by ivashov** [oss-fruct-org/gets#30]
Функция createTrack.php не позволяет изменять имя трека (вместо этого создается новый трек).

Параметр hname в createTrack.php должен быть deprecated (по умолчанию он должен полностью заменять собой name).

Лучше всего сделать новую функцию updateTrack.php, которая будет принимать идентификатор трека, либо если оставлять createTrack.php, то передавать в параметре 'update' id трека для обновления.

**Comment by ivashov** [comment]
Нет, не только обновление имени трека, вообще ничего не работает.

**Comment by seekerk** [comment]
поддерживаю вариант с updateTrack.php
